alias ls='ls --color=auto'
alias ll='ls -l'
alias cls='clear'
alias d2='cap staging deploy; cap test deploy'
alias d3='cap production deploy; cap staging deploy; cap test deploy'
alias dt='cap test deploy'
